version: build{build}

skip_commits:
  files:
    - .travis.yml

environment:
  matrix:
  - MINGW_DIR: mingw64
    MINGW_VER: x86_64-7.2.0-posix-seh-rt_v5-rev1
    WITH_FTDI: ON

clone_folder: c:\dev\pulp-tools
clone_depth: 5

install:
  - git submodule update --init --recursive

before_build:
  - set Path=C:\mingw-w64\%MINGW_VER%\%MINGW_DIR%\bin;%Path%
  - git config --global core.autocrlf input
  - g++ --version
  - mingw32-make --version
  - cmake --version
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - cd c:\dev\pulp-tools
  - md build

build_script:
  - cd build
# Note: The CMAKE_INSTALL_PREFIX avoids mingw picking up the git shell (sh). This variable should be
# propagated into all cmake scripts in submodules
  - cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug -DStandaloneApp=YES  -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/install" -DWithFTDI=$WITH_FTDI -DCMAKE_IGNORE_PATH="C:/Program Files/Git/usr/bin"
  - cmake --build . --target pulp-debug-bridge -- VERBOSE=1
  - 7z a plpbridge_win64.zip %APPVEYOR_BUILD_FOLDER%/install/*

artifacts:
  - path: build/plpbridge_win64.zip
    name: plpbridge_win64

test: off
